# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-23 02:34
from __future__ import unicode_literals

import character.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=24)),
                ('lastname', models.CharField(blank=True, max_length=24, null=True)),
                ('age', models.IntegerField(validators=[django.core.validators.MaxValueValidator(9999, 'No way can they be that old!')])),
                ('img', models.ImageField(blank=True, null=True, upload_to=character.models.upload_location)),
                ('original', models.BooleanField(default=True)),
                ('creator', models.CharField(blank=True, max_length=32, null=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('username', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
