# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-23 02:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=125)),
                ('content', models.TextField(blank=True, null=True)),
                ('private', models.BooleanField()),
                ('publish', models.DateField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('genre', models.CharField(max_length=32)),
                ('style', models.CharField(max_length=122)),
                ('length', models.CharField(max_length=122)),
                ('details', models.TextField(blank=True, null=True)),
                ('cor', models.CharField(max_length=32)),
            ],
        ),
        migrations.DeleteModel(
            name='BlogPost',
        ),
        migrations.DeleteModel(
            name='PromptPost',
        ),
    ]
