# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-23 03:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20161222_2115'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FanPost',
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-timestamp', '-updated']},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='cor',
            new_name='fandom',
        ),
        migrations.AddField(
            model_name='post',
            name='banner',
            field=models.ImageField(blank=True, height_field='100', null=True, upload_to='', width_field='500'),
        ),
        migrations.AddField(
            model_name='post',
            name='rptype',
            field=models.CharField(default='Original', max_length=32),
        ),
        migrations.AddField(
            model_name='post',
            name='type',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='genre',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='length',
            field=models.CharField(blank=True, max_length=122, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='private',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='style',
            field=models.CharField(default='Script', max_length=122),
        ),
    ]
