# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-23 03:56
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20161222_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='max_height',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='post',
            name='max_width',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='post',
            name='banner',
            field=models.ImageField(blank=True, height_field='max_width', null=True, upload_to='', width_field='max_height'),
        ),
    ]
