# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-23 05:04
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20161222_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='genre',
            field=models.CharField(choices=[('Fandom', 'Fandom'), ('Fantasy/Supernatural', 'Fantasy/Supernatural'), ('Historical', 'Historical'), ('Sci-Fi', 'Sci-Fi'), ('Slice of Life', 'Slice of Life'), ('Romance', 'Romance'), ('Horror', 'Horror'), ('Mystery', 'Mystery'), ('Steampunk', 'Steampunk'), ('Cyberpunk', 'Cyberpunk'), ('Victorian Era', 'Victorian Era'), ('Drama', 'Drama')], default='Fandom', max_length=64),
        ),
        migrations.AlterField(
            model_name='post',
            name='max_height',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='post',
            name='max_width',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(500), django.core.validators.MinValueValidator(500)]),
        ),
        migrations.AlterField(
            model_name='post',
            name='pref',
            field=models.CharField(choices=[('None', 'None'), ('Male', 'Male'), ('Female', 'Female'), ('FTM', 'FTM'), ('MTF', 'MTF')], default='None', max_length=64),
        ),
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateField(blank=True, null=True),
        ),
    ]
