# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-12 18:42
from __future__ import unicode_literals

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20160704_1900'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to=home.models.upload_location)),
                ('title', models.CharField(max_length=100)),
                ('about', models.TextField()),
                ('joined_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='staff',
            name='staff',
        ),
        migrations.AlterField(
            model_name='feature',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=home.models.upload_location),
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
